# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Columns
  description: Flexible columns block
  icon: view_column

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
  columns: [bookshop:structure:content_blocks]
  background_color:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
