# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Testimonials Slider"
  description: A testimonial slider block
  icon: format_quote

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Words From Our Clients
  body: "Discover the experiences of those who've partnered with us. Here's what our valued clients have to say about our sustainable solutions."
  testimonials: 
    - body: 
      image: 
      name:
      company:
  background_color:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
