# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Hero"
  description: A generic hero block for interior pages
  icon: auto_fix_normal

# Defines the structure of this component, as well as the default values
blueprint:
  heading: ""
  body: ""
  image:
    image_url:
    image_alt:
  button:
    enabled: true
    button_url: 
    button_text:
    open_in_new_tab: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
