const autoprefixer = require('autoprefixer')
const purgecss = require('@fullhuman/postcss-purgecss')

module.exports = {
  plugins: [
    autoprefixer(),
    purgecss({
      content: [
        './layouts/**/*.html',
        './layouts/**/*.svg',
        './content/**/*.md',
      ],
      safelist: [
        'mobile-dropdown-open',
        'is-active',
        'nav-open',
        'has-dropdown-open',
        'has-sub-menu-open',
        'expand',
        'collapse',
        'page-home',
        'page-about',
        'page-contact',
        'page-clean-energy-home',
        'parent-page-home',
        'parent-page-about',
        'parent-page-services',
        'parent-page-contact',
        'parent-page-blog',
        'active-button',
        'position-open',
        'list-open',
        'toggle-mobile-dropdown',
        'ul', 
        'ol',
        'table',
        'tr',
        'td',
        'pre',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'btn--active',
        'auto-grid',
        'media-text-block',
        'media-text-block__image',
        'media-text-block--text-left',
        'media-text-block--text-right',
        'bg-black',
        'bg-gray',
        'bg-white',
        'grid-columns-3',
        'grid-columns-4',
        'testimonials',
        'testimonials__content',
        'reel',
        'reel__testimonial',
        'reel__body',
        'reel__image',
        'text-align-start',
        'text-align-center',
        'text-align-end',
        'iframe',
        'hero--split-hero',
      ],
    }),
  ],
}