# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Services Feed"
  description: Services feed block
  icon: work

# Defines the structure of this component, as well as the default values
blueprint:
  heading: ""
  body: ""
  services_feed: ""
  background_color: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
